service: go-lambda

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  environment:
    DATADOG_AGENT: 1.2.3.4
  vpc:
    securityGroupIds:
      - sg-1234
    subnetIds:
      - subnet-1234
      - subnet-1234
      - subnet-1234

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/main
    events:
      - http:
          path: hello
          method: get
